FROM ghcr.io/open-webui/open-webui:main

# Use a Custom CSS file
# Content Credit https://sliplane.io/blog/how-to-build-custom-open-webui-themes

USER root:root
#USER 0:0
# Copy your custom CSS file
COPY custom.css /app/build/static/
